version: '3.8'

# NIS v3 Template - Customize ports via env vars like ZOOKEEPER_PORT=2182
# For new versions, copy this file and adjust as needed
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: nis-zookeeper
    networks:
      - nis-network
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: nis-kafka
    networks:
      - nis-network
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  redis:
    image: redis:7-alpine
    container_name: nis-redis
    networks:
      - nis-network
    ports:
      - "6379:6379"

  backend:
    build: .
    container_name: nis-backend
    networks:
      - nis-network
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - kafka

  nginx:
    image: nginx:1.25-alpine
    container_name: nis-nginx
    networks:
      - nis-network
    ports:
      - "80:80"
    volumes:
      - ./system/config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend

volumes:
  zookeeper_data:
  zookeeper_log:
  kafka_data:
  redis_data:

networks:
  nis-network:
    driver: bridge 