import requests
import json
import textwrap

url = "http://localhost:8001/chat"
headers = {"Content-Type": "application/json"}
data = {
    "message": "Explain how the NIS protocol uses KAN and PINN for signal processing.",
    "user_id": "test_user_kan_pinn"
}

print(f"🔬 Querying endpoint: {url}")
print(f"   Payload: {data['message']}\n")

try:
    response = requests.post(url, headers=headers, data=json.dumps(data))
    response.raise_for_status()  # Raise an exception for bad status codes

    print(f"✅ SUCCESS: Status Code {response.status_code}\n")
    
    response_data = response.json()
    
    print("🧠 Full JSON Response:")
    print(json.dumps(response_data, indent=2))
    print("\n" + "="*50 + "\n")

    print("📝 Formatted Response Content:")
    # Wrap the text for better readability
    wrapped_text = textwrap.fill(response_data.get('response', 'No content found.'), width=80)
    print(wrapped_text)
    print("\n" + "="*50 + "\n")

    print("📈 Analysis:")
    reasoning_trace = response_data.get('reasoning_trace', [])
    if 'llm_generation' in reasoning_trace:
        print("  - ✔️ Response correctly indicates LLM generation.")
    else:
        print("  - ❌ Response is missing 'llm_generation' in its reasoning trace.")

    if 'deepseek' in response_data.get('provider', ''):
         print("  - ✔️ Response was generated by the 'deepseek' provider as expected.")
    else:
        print(f"  - ⚠️  Response was generated by an unexpected provider: {response_data.get('provider')}")

    if 'confidence' in response_data and response_data['confidence'] > 0.7:
        print(f"  - ✔️ Confidence score is high ({response_data['confidence']:.2f}).")
    else:
        print(f"  - ⚠️  Confidence score is low or missing ({response_data.get('confidence', 0):.2f}).")


except requests.exceptions.RequestException as e:
    print(f"❌ FAILED: Could not connect to the server.")
    print(f"   Error: {e}")
except json.JSONDecodeError:
    print(f"❌ FAILED: Could not decode the JSON response.")
    print(f"   Received: {response.text}") 