#!/usr/bin/env python3
"""
Deploy OpenFang Agent OS to H100
=================================
1. Installs OpenFang via official installer (~/.openfang/bin/openfang)
2. Writes ~/.openfang/config.toml (vLLM + NIS MCP)
3. Creates ~/.openfang/agents/nis-picker/agent.toml
4. Sets OPENAI_API_KEY=nis-local in ~/.openfang/.env
5. Starts OpenFang on port 4200
6. Verifies http://localhost:4200/api/health

Usage: python _deploy_openfang_h100.py
"""
import json, subprocess, sys, time, urllib.request

SSH = ["ssh", "-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null",
       "awesome-gpu-name"]

sys.stdout.reconfigure(encoding="utf-8", errors="replace")


def run(cmd_str: str, timeout: int = 60) -> tuple[str, int]:
    """Run command on H100 via SSH."""
    result = subprocess.run(SSH + [cmd_str], capture_output=True, text=True, timeout=timeout)
    out = (result.stdout + result.stderr).strip()
    return out, result.returncode


# ── Config files ──────────────────────────────────────────────────────────────

CONFIG_TOML = """\
# OpenFang config — NIS Protocol integration
# Generated by _deploy_openfang_h100.py

[default_model]
provider    = "openai"
model       = "qwen35-nis"
api_key_env = "OPENAI_API_KEY"
base_url    = "http://localhost:8701/v1"
max_tokens  = 4096
temperature = 0.1

[[mcp_servers]]
name         = "nis-protocol"
timeout_secs = 60

[mcp_servers.transport]
type = "http"
url  = "http://localhost:8090/openfang/mcp"
"""

NIS_PICKER_TOML = """\
name        = "nis-picker"
version     = "0.1.0"
description = "Autonomous xArm cookoff agent — picks all lighters from table via NIS Protocol"
author      = "nis-team"
module      = "builtin:chat"
tags        = ["robotics", "arm", "nis", "cookoff"]

[model]
provider    = "openai"
model       = "qwen35-nis"
api_key_env = "OPENAI_API_KEY"
base_url    = "http://localhost:8701/v1"
max_tokens  = 4096
temperature = 0.1
system_prompt = \"\"\"You are nis-picker, an autonomous robotic arm control agent for the NIS Protocol cookoff challenge.

You control an xArm 6DOF arm via NIS Protocol MCP tools. Your job: detect all lighters on the table and pick them into the bin.

AVAILABLE MCP TOOLS (call these directly via tool use):
- cookoff_autonomous(execute_arm, max_picks, max_retries, conf) — full YOLO+Cosmos+arm sweep
- camera_snapshot() — get current camera frame (returns base64 image)
- arm_get_status() — check current servo positions
- arm_move_home() — send arm to safe home position
- cosmos_reason(task, image_base64) — ask Cosmos Reason2 about the scene
- system_status() — check Pi agent + Cosmos health

WORKFLOW:
1. Call camera_snapshot() to see current workspace
2. Call cookoff_autonomous(execute_arm=false, max_picks=10) — simulate first
3. Report results: picks_success / picks_total / table_clear
4. If user confirms real run: call cookoff_autonomous(execute_arm=true)
5. Store results: memory_store(key="last_cookoff", value=results)

SAFETY:
- ALWAYS default to execute_arm=false (simulation) unless user explicitly says "real", "live", or "execute"
- Before any real arm move, call arm_get_status() to verify arm is responsive
- If arm_get_status() fails, abort and report

After each run, summarize: picks made, objects left, table_clear status.\"\"\"

[resources]
max_llm_tokens_per_hour = 100000
max_concurrent_tools    = 5

[capabilities]
tools        = ["shell_exec", "memory_store", "memory_recall", "agent_send"]
network      = ["localhost:8090", "localhost:8701"]
memory_read  = ["*"]
memory_write = ["self.*", "shared.cookoff.*"]
shell        = ["curl *"]
"""


def write_remote_file(path: str, content: str) -> bool:
    """Write content to a remote file via Python stdin."""
    import base64
    b64 = base64.b64encode(content.encode()).decode()
    cmd = f"python3 -c \"import base64,os; os.makedirs(os.path.dirname('{path}'),exist_ok=True); open('{path}','wb').write(base64.b64decode('{b64}'))\""
    out, rc = run(cmd)
    return rc == 0


def main():
    print("\n=== Deploy OpenFang to H100 ===\n")

    # [0] Check if OpenFang already installed
    print("[0] Checking existing OpenFang installation...")
    out, rc = run("~/.openfang/bin/openfang --version 2>/dev/null || openfang --version 2>/dev/null || echo NOT_INSTALLED")
    if "NOT_INSTALLED" in out:
        print("  Not installed — running installer...")
        print("  (This may take 30-60s)")
        out, rc = run("curl -fsSL https://openfang.sh/install | sh 2>&1", timeout=120)
        print(f"  {out[-200:] if len(out)>200 else out}")
        if rc != 0 and "installed" not in out.lower() and "openfang" not in out.lower():
            print("  WARN: Installer may have failed, trying cargo install...")
            out, rc = run(
                "cargo install openfang-cli --quiet 2>&1 | tail -5",
                timeout=300
            )
            print(f"  cargo: {out}")
    else:
        print(f"  Already installed: {out.strip()}")

    # [1] Write config
    print("\n[1] Writing ~/.openfang/config.toml...")
    run("mkdir -p ~/.openfang/agents/nis-picker")
    if write_remote_file("~/.openfang/config.toml", CONFIG_TOML):
        print("  OK: config.toml")
    else:
        print("  FAIL: config.toml")

    # [2] Write .env
    print("\n[2] Writing ~/.openfang/.env...")
    env_content = "OPENAI_API_KEY=nis-local\nRUST_LOG=info\n"
    if write_remote_file("~/.openfang/.env", env_content):
        print("  OK: .env")
    else:
        print("  FAIL: .env")

    # [3] Write nis-picker agent
    print("\n[3] Writing nis-picker agent...")
    if write_remote_file("~/.openfang/agents/nis-picker/agent.toml", NIS_PICKER_TOML):
        print("  OK: agents/nis-picker/agent.toml")
    else:
        print("  FAIL: agents/nis-picker/agent.toml")

    # [4] Kill existing OpenFang if running
    print("\n[4] Stopping any existing OpenFang process...")
    run("kill $(lsof -ti :4200) 2>/dev/null || fuser -k 4200/tcp 2>/dev/null; sleep 1")
    print("  OK")

    # [5] Start OpenFang
    print("\n[5] Starting OpenFang on port 4200...")
    OPENFANG_BIN = "~/.openfang/bin/openfang"
    start_cmd = (
        f"export OPENAI_API_KEY=nis-local; "
        f"export OPENFANG_HOME=~/.openfang; "
        f"nohup {OPENFANG_BIN} start --config ~/.openfang/config.toml "
        f"> /tmp/openfang.log 2>&1 & echo pid=$!"
    )
    out, rc = run(start_cmd, timeout=15)
    print(f"  {out or '(no output)'}")

    # [6] Wait and verify
    print("\n[6] Waiting 8s for startup...")
    for i in range(8):
        time.sleep(1); print(f"  {'.'*(i+1)}", end="\r")
    print()

    out, rc = run("curl -sf http://localhost:4200/api/health 2>/dev/null || echo FAIL")
    if "FAIL" in out or rc != 0:
        print(f"  WARN: Health check failed — {out[:100]}")
        print("  Checking log...")
        log_out, _ = run("tail -15 /tmp/openfang.log 2>/dev/null")
        print(f"  Log: {log_out}")
    else:
        try:
            d = json.loads(out)
            print(f"  OK: OpenFang health — {d}")
        except Exception:
            print(f"  Response: {out[:200]}")

    # [7] List agents
    print("\n[7] Listing agents...")
    out, rc = run("curl -sf http://localhost:4200/api/agents 2>/dev/null || echo FAIL")
    if "FAIL" not in out:
        try:
            d = json.loads(out)
            print(f"  Agents: {d}")
        except Exception:
            print(f"  Response: {out[:200]}")
    else:
        print("  Agents endpoint not available — OpenFang may still be starting")

    print("\n=== Done ===")
    print("  OpenFang:   http://localhost:4200  (H100 local)")
    print("  Dashboard:  http://localhost:4200/dashboard")
    print("  nis-picker: send message via POST /api/agents/nis-picker/message")
    print("\n  To test:")
    print("  ssh awesome-gpu-name 'curl -X POST http://localhost:4200/api/agents/nis-picker/message")
    print("    -H \"Content-Type: application/json\"")
    print("    -d \\'{{\"content\": \"scan the table in simulation mode\"}}\\''")


if __name__ == "__main__":
    main()
